---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - access-manager.github.com
  resources:
  - oktagroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - access-manager.github.com
  resources:
  - oktagroups/finalizers
  verbs:
  - update
- apiGroups:
  - access-manager.github.com
  resources:
  - oktagroups/status
  verbs:
  - get
  - patch
  - update
